import { PluginSettings } from './types';

// List of supported Gemini models
export const GEMINI_MODELS = [
	'gemini-2.5-pro-exp-03-25',
	'gemini-2.0-flash',
	'gemini-2.0-flash-lite',
	'gemini-1.5-flash',
	'gemini-1.5-flash-8b',
	'gemini-1.5-pro',
] as const;

// Default prompt for video analysis
export const DEFAULT_PROMPT = `You are a specialized assistant for creating comprehensive video summaries from subtitles. The subtitles have been automatically generated by YouTube and may contain transcription errors, especially with technical terms, software names, and specialized vocabulary.

## Task

Create a concise yet comprehensive summary of the video based on the provided subtitles.

## Handling Transcription Errors

- Correct obvious transcription errors based on context and your domain knowledge
- Pay special attention to technical terms, software names, programming languages, and IDE plugins which are frequently misrecognized
- If multiple interpretations are possible, choose the most likely one based on the video's context

## Output Structure

` + "```" + `
## Summary
[Write a comprehensive summary of the main topic and key message]

## Key points
- [Key point 1]
- [Key point 2]
- [Additional key points...]

## Technical terms
- **[[Term 1]]**: [Explanation of term 1]
- **[[Term 2]]**: [Explanation of term 2]
- [Additional terms as needed...]

## Conclusion
[Write a brief conclusion]
` + "```" + `

Note: Include all sections. If there are no technical terms, omit that section entirely.`;

// Default settings for the plugin
export const DEFAULT_SETTINGS: PluginSettings = {
	customPrompt: DEFAULT_PROMPT,
	selectedProvider: '', // Default to no provider selected
};

// Regex pattern for extracting video ID from YouTube URL
export const VIDEO_ID_REGEX = /(?:v=|[\/])([a-zA-Z0-9_-]{11})/;

// YouTube URLs
export const WATCH_URL = 'https://www.youtube.com/watch?v=';

// InnerTube API
export const INNERTUBE_API_KEY_REGEX = /"INNERTUBE_API_KEY":\s*"([a-zA-Z0-9_-]+)"/;
export const INNERTUBE_API_URL = 'https://www.youtube.com/youtubei/v1/player?key=';
export const INNERTUBE_CONTEXT = {
    client: {
        clientName: 'ANDROID',
        clientVersion: '20.10.38',
    },
};
